config/routes.rb
Rails.application.routes.draw do

  root 'questions#index'
  get 'answer' => 'questions#answer'
  resources :questions, except: :index do
    post :answer, on: :member
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
  
  after_initialize :modify_answer
  before_update :modify_answer
  validates :question, uniqueness: { case_sensitive: true }
  validates_presence_of :answer

  require 'numbers_in_words'
  def is_correct?(submission)
  	#default is to remove white spaces and to lower case the input
  	#when converting number to words, I had to remove "and " because of a bug in the gem
	  submission = submission.to_s.downcase.gsub(/\s+/, '')
	  if(is_a_number(submission))
	  	submission = NumbersInWords.in_words(submission).gsub("and ", "").gsub(/\s+/, '')
	  end
	  answer == submission
  end

  protected

    def modify_answer
      	input = answer.to_s.downcase.strip.gsub(/\s+/, '')
   		if(is_a_number(input))
			input = NumbersInWords.in_words(input).gsub("and ", "").gsub(/\s+/, '')
		end
		self.answer = input
    end

    def is_a_number answer
	  true if Float(answer) rescue false
	end

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
  before_filter :find_question, only: [:show, :edit, :update]

  def index
    @questions = Question.all
  end

  def new
    @question = Question.new
  end

  def create
    @question = Question.new question_params
    if @question.answer.empty? || @question.question.empty?
      redirect_to :back, notice: 'Input was not saved because question and/or answer were/was empty.'
    elsif @question.save
      render '/questions/answer.html.haml', {question: @question}
    else
      render :new
    end
  end

  def update
    if @question.update_attributes question_params
      redirect_to root_path, notice: 'Question saved successfully.'
    else
      render :edit
    end
  end

  def answer
    @answer = find_question.answer
    if is_empty? params
      redirect_to :back, notice: 'Input is blank. Please give an answer.'
    elsif(right_answer(@answer))
      redirect_to root_path, notice: 'You have input the right answer!'
    else
      redirect_to root_path, notice: 'You have input the wrong answer.'
    end
  end

  private

    def is_empty? params
      params["Answer"].empty?
    end

    def right_answer answer
      require 'numbers_in_words'
      input = params["Answer"].to_s.downcase.strip.gsub(/\s+/, '')
      if(is_a_number(input))
        input = NumbersInWords.in_words(input).gsub("and ", "").gsub(/\s+/, '')
      end
      answer == input
    end

    def is_a_number answer
      true if Float(answer) rescue false
    end

    def find_question
      @question = Question.find(params[:id])
    end

    def question_params
      params.require(:question).permit(:question, :answer)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/application/_nav.html.haml
%nav.navbar.navbar-default.navbar-fixed-top
  .container-fluid
    .navbar-header
      %button.navbar-toggle.collapsed{type: "button", data: { toggle: "collapse", target: "#bs-example-navbar-collapse-1" }}
        %span.sr-only Toggle navigation
        %span.icon-bar
        %span.icon-bar
        %span.icon-bar

      %a.navbar-brand{href: root_path}
        Quiz Master

    .collapse.navbar-collapse#bs-example-navbar-collapse-1
      %ul.nav.navbar-nav
        -# Page links can go here
          %li.active
          %a{href: '#'} Link

app/views/layouts/application.html.haml
!!!
%html{"ng-app" => "quizmaster"}
  %head
    %title Quiz Master
    = stylesheet_link_tag    'application', media: 'all'
    = javascript_include_tag 'application'
    = csrf_meta_tags

  %body
    = render "nav"

    - if flash[:notice].present?
      .container
        .alert.alert-info
          = flash[:notice]

    = yield

app/views/questions/_form.html.haml
= form_for @question do |f|

  - if @question.errors.present?
    .alert.alert-danger
      - @question.errors.full_messages.each do |message|
        .message= message

  .well
    .form-group.form-header
      = f.label :question
      = f.text_field :question, class: 'form-control'
    .form-group.form-header
      = f.label :answer
      = f.text_field :answer, class: 'form-control'

  = f.submit "Submit", class: 'btn btn-default'

app/views/questions/answer.html.haml
.container
  %h1 Question created successfully!

  .well
    %h3 Question
    %p=  @question.question
    %h3 Answer
    %p=  @question.answer

app/views/questions/edit.html.haml
.container

  %h1 Edit the Question
  = render 'form'

app/views/questions/index.html.haml
.container
  %h1 Choose a Question
  
  %div{"ng-controller" => "changecolorCtrl"}
    = link_to "Add a new question", new_question_path, :required => true, :class => "btn btn-default", style: "float:right;"
    .input-group-btn
      %button.btn.btn-default{:type => "button", 'ng-click' => "red()"} Red
      %button.btn.btn-default{:type => "button", 'ng-click' => "violet()"} Violet 
      %button.btn.btn-default{:type => "button", 'ng-click' => "green()"} Green
      %button.btn.btn-default{:type => "button", 'ng-click' => "pink()"} Pink
      %button.btn.btn-default{:type => "button", 'ng-click' => "black()"} Black
    .well
      .list-group
        - @questions.each do |question|
          .list-group
            .question
              = link_to question.question, question, :class => "list-group-item button",style: "color:{{color}}"
              = link_to "Edit the question", edit_question_path(question), :class => "editquestion", style: "float:right;"

 

app/views/questions/new.html.haml
.container

  %h1 New Question
  = render 'form'

app/views/questions/show.html.haml
.container
  %h1 Question time...

  .well
    %p= @question.question

    = form_for :answer, url: answer_question_path(@question) do |f|
      .form-group
        = f.text_field :answer, class: 'form-control', :align => 'right', :name =>"Answer"

      = f.submit "Submit answer", class: 'btn btn-default'